### ISSUE TITLE
時間外労働の割増賃金率引き上げへの対応

### ISSUE THREAD

**Issue by knokmki612** [tuqulore/employee-handbook#109]
２０２３年４月１日から月６０時間を超える時間外労働の割増賃金率が引き上げられます
https://www.mhlw.go.jp/content/000930914.pdf

以下の箇所への対応が必要かと思った

https://github.com/tuqulore/employee-handbook/blob/5f98c355ab5b07f5cd83d57a9d84de9e80de412e/02_%E8%B3%83%E9%87%91%E8%A6%8F%E7%A8%8B.md?plain=1#L47-L48

**Comment by knokmki612** [comment]
変更案

```diff
   1. 法定時間外労働手当は、法定時間を超える労働時間分の賃金として、次の算式により計算して支給する。 
-     - `法定時間外労働手当 = 基本給 × 1.25 × 法定時間外労働の時間数`
+     - `法定時間外労働手当 = 基本給 × (1.25 × 60時間以下の法定時間外労働の時間数 + 1.50 × 60時間超の法定時間外労働の時間数)`
```

**Comment by Tomo416** [comment]
ありがとうございます。
