### ISSUE TITLE
決算賞与

### ISSUE THREAD

**Issue by knokmki612** [tuqulore/employee-handbook#41]
#10 で挙がっていた。
賞与の条項と別途追加するか検討する。初回の就業規則施行には含めない

Takashi-Uさんのコメント

> これは私のジャンルではなく、会計士さんや税理士さんにご確認いただけたらと思いますが、一般的には支出に正当な理由があるから損金（会社の経費）に算入されますので、規程等の根拠がない中での支出は度が過ぎると問題があるかもしれません。
> 金額の多寡や頻度にもよるかもしれませんので、また会計の専門家にご相談の上ご検討ください。最悪でも、決算賞与を金額が現物で支給することがあるという条項はあっても良いかもしれませんね。

- [x] 会計士さんに決算賞与を定める場合の適切な金額等相談する

**Comment by Hidetaro7** [comment]
福島会計 山田さんから連絡ありました。

以下、引用になります。

---

ご連絡ありがとうございます。
使用人（役員以外）の決算賞与につきまして、規定や金額の基準がないと法人税の損金算入にあたって不都合が生じるかどうかというご相談かと思います。

法人税法では、使用人賞与を3種類に分けて、損金算入の時期を規定しています。
１．就業規則等に規定するものは、規定した支給予定日に損金算入（夏・冬の賞与など）
２．３要件を満たすものは、支給額の個別通知日に損金算入（決算賞与）
３．それ以外は、支払日に損金算入

つまり、２．に該当する決算賞与は、規定がなくても要件を満たすことで通知日の損金に算入できます。
要件は、次の3つです。
イ その支給額を、各人別に、かつ、同時期に支給を受ける全ての使用人に対して通知をしていること。
ロ イの通知をした金額を通知した全ての使用人に対しその通知をした日の属する事業年度終了の日の翌日から1か月以内に支払っていること。
ハ その支給額につきイの通知をした日の属する事業年度において損金経理をしていること。

これらの要件をすべて満たさないと3月の損金としたかったのに、4月の損金となってしまうことになります。
もっとも、貴社は3月賞与が規定されていますので、わざわざ決算賞与とせずに3月賞与として支給することが無難と考えます。
基準につきましても不正を疑わざるを得ないような金額でなければ問題ないと考えます。

**Comment by knokmki612** [comment]
> もっとも、貴社は3月賞与が規定されていますので、わざわざ決算賞与とせずに3月賞与として支給することが無難と考えます。

損金算入を支給額の個別通知日にするために三要件を満たすための業務管理を別に検討するのは大変そうなので、決算賞与は定めなくていいように思った

**Comment by knokmki612** [comment]
> 決算賞与は定めなくていいように思った

社内で検討した結果、定めないという結論になった
