### ISSUE TITLE
定期健康診断

### ISSUE THREAD

**Issue by knokmki612** [tuqulore/employee-handbook#52]
実施の流れは今年はこのようにする

1. 事前に以下の2点を共有して承認を得る
    - 労働安全衛生法に基づく定期健康診断を実施している病院
    - 労働安全衛生法に基づく定期健康診断を受けた場合の費用
2. 健診を受ける
3. 健康診断書の提出とともに費用の精算をする

気になる点

1. 定期健診は各人受ける時期はバラバラでも問題ないが、時期を決めてもいいと思うのでどうするか
2. 定期健診の受診時間を労働時間として取り扱うか：義務ではないが取り扱ってもらえる分には嬉しくはある
3. 定期健診の費用が別途精密検査など必要となった場合の差額を自己負担とするか：定期健診は保険適用外だが精密検査は保険適用になる

社内で話した結果

1. 6月にする
2. 保留(各人で時間が違ったり待ち時間が長かったりするので抵抗がある)
3. 保留(差額をある程度負担したい気持ちもあるが、どの程度の費用になるか分からない)

**Comment by knokmki612** [comment]
> 3\. 定期健診の費用が別途精密検査など必要となった場合の差額を自己負担とするか：定期健診は保険適用外だが精密検査は保険適用になる

各人の健康のことを考えるのであれば、たとえば法定の検査項目相当の費用(相場的には5000円〜15000円)をカバーする額として、上限を15000円と定め、それ以上の検査項目を含んだ人間ドックなどを定期健康診断時に受けられるようにする、という仕組みはどうだろうという話をした。

今年の定期健康診断はそうしてみるかなど、随時相談していく

**Comment by knokmki612** [comment]
> 各人の健康のことを考えるのであれば、たとえば法定の検査項目相当の費用(相場的には5000円〜15000円)をカバーする額として、上限を15000円と定め、それ以上の検査項目を含んだ人間ドックなどを定期健康診断時に受けられるようにする、という仕組みはどうだろうという話をした。
> 
> 今年の定期健康診断はそうしてみるかなど、随時相談していく

2021年の定期健康診断は、会社が負担する費用は20000円を上限とし、定期健康診断を実施した。

**Comment by Takashi-U** [comment]
検査項目についてですが、実際に、従業員の希望で検査項目を増やす会社も一定数あります。その場合、私の知る範囲では定期健康診断にかかる費用以外は個人負担にしている会社がほぼ全てです。
規則とは関係無い話ですが、地域の公共団体や健康保険組合によっては健診に対する補助を行っている所があります。そういった補助が受けられそうならば、それと絡めて対応を考えるのがベターかと思います。

定期健診の受診時間の件も挙げられていますが、せっかく実施時期を決められたわけですから、選択肢としては有給の計画付与を行うという事も考えられます。もしも、有給の消化率が低いようであれば、有力な選択肢かと思います。

**Comment by knokmki612** [comment]
> 検査項目についてですが、実際に、従業員の希望で検査項目を増やす会社も一定数あります。その場合、私の知る範囲では定期健康診断にかかる費用以外は個人負担にしている会社がほぼ全てです。

そうすると法定検査項目までの実費まで負担する、のような規則にしたほうがいいのでしょうかね…？
実務的には事業所単位で一斉実施のようなことはしておらず、個別に病院に予約しておこなっています。その際会社負担と個人負担の切り分けが難しいこともあり、上限額を設けることで対応しているつもりですね（おそらく病院ごとには別々に領収書を切ってくれるなどしてくれるところもあるだろうが、どこの病院でもやってくれるかは不明）

> 規則とは関係無い話ですが、地域の公共団体や健康保険組合によっては健診に対する補助を行っている所があります。そういった補助が受けられそうならば、それと絡めて対応を考えるのがベターかと思います。

そうですね、健康保険組合から定期的な案内もあるので、該当者は受けられる補助を見落とさないですむような工夫がしたいところですが、今のところ会社として具体的な該当者へのサポートはしていないです（おそらく現状は誰かが気づいたら該当者に社内ミーティングでお知らせする程度）

> 選択肢としては有給の計画付与を行うという事も考えられます。もしも、有給の消化率が低いようであれば、有力な選択肢かと思います。

今のところ年末年始等まとめて有給取得することが多く、各社員の有給の消化率は問題ないかと思います。

また、法定の検査項目だけの場合半日程度で検査が完了し当日勤務することも可能なので、各人の判断で有給取得する現状でよいかなと思いました。

**Comment by knokmki612** [comment]
> 検査項目についてですが、実際に、従業員の希望で検査項目を増やす会社も一定数あります。その場合、私の知る範囲では定期健康診断にかかる費用以外は個人負担にしている会社がほぼ全てです。

言及した会社負担と個人負担の切り分けが難しい点について、受診する病院の法定検査項目の実費分負担する（たとえばある病院で生活習慣病健診を申し込んだが、会社は同じ病院の定期健康診断の費用分負担）、のような理屈がありえるかなと思いました。
