### ISSUE TITLE
法定休日を日曜日に特定する

### ISSUE THREAD

**Issue by knokmki612** [tuqulore/employee-handbook#56]
現在法定休日がいつなのか就業規則に記載がなく、法定休日が特定できない。
勤怠管理上、毎週日曜日を法定休日扱いにしているため、就業規則にも日曜日を法定休日としていることを明記する

**Comment by Takashi-U** [comment]
法的には、「結果的に1週間のうちに1日（あるいは4週4日）の休日をとること」が求められており、それを満たす休みの事をいわゆる法定休日と言います。ここでポイントとしては、法定休日は必ずしも特定する必要は無いという事です。
ただし、法定休日を特定するというのは会社の運営を行うにあたっては便利な側面もあり、実際に、私の感覚的には就業規則で特定をしている会社というのはそれなりの数になっていると思います。

実態にもあっているという事なので、御社の場合は法定休日を就業規則で特定する方が良いように私も思います。

記載方法は色々考えられますが、シンプルに第24条に第4項を追加して、

4.特に個別の契約で定めが無い場合、第1項第1号の休日を法定休日とする。

程度の記述で差し支え無いと思います。

**Comment by knokmki612** [comment]
developブランチに反映済みなので閉じますね
