### ISSUE TITLE
生理休暇

### ISSUE THREAD

**Issue by knokmki612** [tuqulore/employee-handbook#57]
生理休暇の使用目的が明快であることが、逆に私生活のプライバシーを侵しかねないのと、そのことが休暇の使用を妨げる要因になるのではと思った。

病気休暇が色々な範囲をカバーできるので、生理休暇は廃止して同じ用途では病気休暇を申請してもらうのでどうかなと思った。

**Comment by Hidetaro7** [comment]
確かに主に女性がこの休暇対象として多いと思うので、心理的印象も考慮したほうがいいかもですね。
病気休暇の範囲内でよいと思います。

**Comment by Takashi-U** [comment]
改定の趣旨としては理解できますし、一個人としては賛同したいところではあります。
しかし、古の魔法である労働基準法においては、生理で体調が悪いときに当該労働者の請求によって休みをとらせる事が、会社に義務づけられています。
廃止すると働基準法に対応出来ていない規則になってしまいます。

このissueの意図をくんでどう改定するかという事を考えますと、

1. 第38条第2項については第41条に委任する（生理日の就業が著しく…（中略）…請求があったときは、第41条に基づき必要な期間休暇を与える。）
2. 第41条病気休暇の中に生理を入れ込む（項のタイトルは「病気等休暇」にして、条文の内容にも適宜入れ込む）

後は、このissueでの指摘通り、病気であろうが生理であろうが、第41条適用で対応をすれば良いかと思います。
付け加えると、理由を隠匿する事は良い部分でもありますし、一方でずる休みの温床になる可能性もあります。この部分は第2項および第3項の運用をどうするのか、検討をする必要はあるかもしれません。
現在の条文を解釈すれば、5日までの範囲であれば「体調不良で2、3日休みます」程度の報告で良いと読めます。実情に応じて検討は必要かもしれませんが、妥当な印象は持っています。これであれば、懸案の生理休暇の件は殆ど解決かと思います。（就業困難が5日を超えるような方については個別対応が必要にはなるでしょう。）

**Comment by Tomo416** [comment]
病気休暇としていただけるのはありがたいです。

**Comment by Takashi-U** [comment]
先ほどマージしましたので、条文の改正としては、こちらはクローズしてもよいのかなと思う次第です。
#71 もクローズで良いように思いました。いかがでしょうか。

**Comment by knokmki612** [comment]
はい、完了とするので異存ないです。余談になりますが、PRをマージした際自動的にこちらも閉じられるよう設定したはずなのですが、うまく動作していないようです。原因が分かり次第対応しようと思います（それまでは手動で閉じることになるかと思います）

> https://github.com/tuqulore/employee-handbook/issues/71 もクローズで良いように思いました。いかがでしょうか。

申請のタイミングについてなんらかの規則の追加が必要かと思っていましたが、欠勤の取り扱いがそのまま適用されるということでとくに追加は不要と理解しました

https://github.com/tuqulore/employee-handbook/blob/master/01_%E5%B0%B1%E6%A5%AD%E8%A6%8F%E5%89%87.md#%E7%AC%AC21%E6%9D%A1%E6%AC%A0%E5%8B%A4
