### ISSUE TITLE
深夜業の取扱い

### ISSUE THREAD

**Issue by knokmki612** [tuqulore/employee-handbook#65]
[フレキシブルタイム](https://github.com/tuqulore/employee-handbook/blob/master/01_%E5%B0%B1%E6%A5%AD%E8%A6%8F%E5%89%87.md#%E7%AC%AC30%E6%9D%A1%E3%83%95%E3%83%AC%E3%82%AD%E3%82%B7%E3%83%96%E3%83%AB%E3%82%BF%E3%82%A4%E3%83%A0)に深夜帯を含めていないので、深夜業は基本的には想定していない。

しかし、就業規則を運用している過程で実態として深夜業が発生しうることが判明したので、深夜業の取扱いについて明文化する必要があると思った。

要点

- 深夜業は常態化したくない
- 深夜業は事後的に申告されることが考えられる

**Comment by Takashi-U** [comment]
残業等は結局の所規則だけでは解決しないので、できる工夫も限られるところです。
考えられる工夫としては、

1. フレキシブルタイムの調整
2. 指示に違反して度々深夜に労働する人については懲戒対象とする
3. ある程度の深夜時間数は固定的に深夜割増として支払う

といった所でしょうか。
3番目はそもそもの要点からすれば策にはなりませんが、要点の一部、全部をあきらめるということならば選択肢として浮上してきます。

フレキシブルタイムの調整については、現在の「5時から22時」を例えば「7時から20時」みたいな形にする事を想定しています。そうすると、多少過ぎても深夜にかかる事はありませんし、社員同士での打ち合わせ等を22時ギリギリに設定しないようになります。
規則上の工夫や、実務的な工夫をして、通常ならば深夜に働く必要は無く、かつ、会社からもしないように指示があった場合において、それでも勝手に深夜勤務をするようならば、そこはルール違反になりますので懲戒の対象になってくるかと思います。こちらも程度問題ではありますので、事前に想定をしておく事になるかと存じます。

**Comment by Takashi-U** [comment]
2に対するコメントについては、その深夜の必要性というのも影響してきますので、その点はご留意ください。

例えば、納期が迫っているとして、とはいえ通常の勤務の中では対応が出来ないという状況があったとしたら、深夜労働も致し方無いと評価される可能性は高いです。それを避けるには、納期を超えて会社に損害が出ても良いから深夜は働くなという、強い指示が必要になってきます。

また、労働者の主観で、深夜労働の必要性を感じる・主張するというケースもあり得ますが、その場合にも前述のように明確に指示をする方が望ましいですし、あるいはいちいち指示が出せないにしても、客観的に必要の無い深夜労働という事を証明できるようにしなければなりません。

懲戒をする以上はある程度こういった対応が必要ですし、逆に指示に従わないのならば、最終的には懲戒せざるを得なくなります。

この辺りは人間関係や仕事の状況などの様々な要因が絡まってくるので、規則の事だけでは無くて雰囲気的なものも重要になろうかと存じます。

**Comment by knokmki612** [comment]
> それを避けるには、納期を超えて会社に損害が出ても良いから深夜は働くなという、強い指示が必要

おそらく1回の深夜労働の報告が仮に雇用者視点で適切でなかったとして、その1回で懲戒するというのは考えにくく（客観的に必要のない深夜労働の証明が困難であるため）、「指示に従わなかった」というステップが踏まれるようなしくみになっていないといけないのだろうなと思いました。

深夜労働をしてはいけない期間を個別に定めるような措置がとることがある、など？

> この辺りは人間関係や仕事の状況などの様々な要因が絡まってくる

そうですね…懲戒の事由を検討するにせよ適切な運用がなされるにはどのような書きぶりが妥当かは慎重に検討したいと思いました
