### ISSUE TITLE
支払日に幅をもたせたい

### ISSUE THREAD

**Issue by knokmki612** [tuqulore/employee-handbook#87]
たとえば年末年始など、休日ではないが銀行が振込業務を停止するケースなどにおいて、当月末日に支払いが難しい。締め日以降前もって支払い可能なのであれば、ある程度幅を持って支払い日を決められたほうが円滑に業務がおこなえるかと思った。

```diff
- 1. 賃金は、毎月20日に締め切って計算し、当月末日に支払う。ただし、支払日が休日に当たる場合は、その前日に繰り上げて支払う。
+ 1. 賃金は、毎月20日に締め切って計算し、当月末日までに支払う。ただし、支払日が休日に当たる場合は、その前日に繰り上げて支払う。
```

https://github.com/tuqulore/employee-handbook/blob/master/02_%E8%B3%83%E9%87%91%E8%A6%8F%E7%A8%8B.md#%E7%AC%AC11%E6%9D%A1%E8%B3%83%E9%87%91%E3%81%AE%E8%A8%88%E7%AE%97%E6%9C%9F%E9%96%93%E5%8F%8A%E3%81%B3%E6%94%AF%E6%89%95%E6%97%A5

**Comment by Takashi-U** [comment]
賃金の支払には5つの原則がありまして、そのうちの一つに「一定期間払い」という原則があります。

https://www.mhlw.go.jp/bunya/roudoukijun/faq_kijyungyosei05.html

こちらの厚生労働省のページにもありますが、賃金支払いの間隔が長くならないようにする趣旨です。
この案だと、理論上は6月21日～7月20日の給与を7月21日に支払い、翌月7月21日～8月20日の給与を8月31日に支払った場合に42日間隔があいてしまいます。
私も、どこまでの間隔ならOKかというのはあまり気にしていないので、エビデンスまできちんと確認はしておりませんが、よく見聞きするNG例として、月給の場合で「毎月第1月曜日」といった1週間の幅があるのはダメといったものが挙げられます。
（あまり気にしていないのは、毎月○○日とか、毎月末日にしてしまえばOKなので、あえてNGかどうかの線を突く必要が無いという考えからです。）

先ほどのNG例が正しいとすれば、この案は問題があるかと思います。

もう1点、「末日まで」という表現だと「1日から末日まで」を差すために問題があるという事もあります。

恐らく、前述の例のとおり21日から末日というのを想定しているのではないかと思います。しかし、あまりなじみが無いかもしれませんが、会社によっては「末日締め、当月25日払い」みたいな予め払って、次の月に調整する会社もあります。（古くからある会社にたまに見られるのですが、恐らく入社してから給与が入るまでの間隔を短くする効果を狙っていると思われます。）
そういった事から、「まで」に対応する「から」が論理的には必要だと思いますが、そもそもそういった表現というか決め方はNGなのだと思われます。

これも恐らくですが、法のスタンスとしては、暦や年末年始の金融機関の営業日は法で決まっており、毎月末日に不可抗力で支払えないものは仕方が無いという立場から、渋々、支払日が若干変わることを許容していると思われます。
この観点からすれば、結果的に幅が出るのは良いが、狙って幅を持たすのはNGとなります。

事務処理の改善という趣旨から考えますと、支払日に幅を持たせるというやり方ではなくて、締め日をさらに前にするという形が考えられます。例えば、15日締めにして、25日くらいに振込予約を基本とし、シルバーウィーク等で連休があるときは振込期限まで作業をすれば、暦等にあまり影響されずに毎月10日間の作業時間がとれます。

この辺りを念頭にご検討いただければと存じます。

**Comment by knokmki612** [comment]
ご指摘ありがとうございます！

> 賃金支払いの間隔が長くならないようにする趣旨

おっしゃるとおり幅をもたせることを規則として定めてしまうと、支払い期間の長短が生じ一定期間払いの原則を満たせなくなるかと思いました。

> 暦や年末年始の金融機関の営業日は法で決まっており、毎月末日に不可抗力で支払えないものは仕方が無いという立場から、渋々、支払日が若干変わることを許容していると思われます。

> 事務処理の改善という趣旨から考えますと、支払日に幅を持たせるというやり方ではなくて、締め日をさらに前にするという形が考えられます。

締め日の変更は業務の見直しが必要になり、担当者への負担が生じるかと推測します。一度締め日の変更が歓迎されることか確認しようかと思います。

現状でコンプライアンス的にことさらに問題がないのであれば、あえて変更する必要はないように思いました。このissueについては閉じまして、締め日の変更は社内で相談したのち必要ということになりましたら別途issueにしようかと思います。

**Comment by knokmki612** [comment]
> 締め日の変更は業務の見直しが必要になり、担当者への負担が生じる

変更範囲の洗い出しがまず大変な印象 @Tomo416 という指摘いただいた
