### ISSUE TITLE
企業型確定拠出年金への対応

### ISSUE THREAD

**Issue by knokmki612** [tuqulore/employee-handbook#88]
企業型確定拠出年金を導入することが決まったので、そのための就業規則の対応が必要になった。
導入支援を受けており支援者から指摘事項が挙がってきている。

何らかのかたちで指摘事項を分割整理して個別に検討、反映できれば完了。

**Comment by knokmki612** [comment]
いただいた変更案 
[就業規則.docx](https://github.com/tuqulore/employee-handbook/files/10319031/default.docx)

**Comment by knokmki612** [comment]
issueにしていない大きな変更としては、アルバイト社員の区分の削除があるが、こちらは雇い入れる想定があるから記載している旨伝えたところ、残す方針となったので無視してよい

**Comment by Tomo416** [comment]
就業規則の改正が終わったら雨包さんにご連絡する

**Comment by knokmki612** [comment]
以下が残タスクの状態です

- [ ] https://github.com/tuqulore/employee-handbook/pull/108
- [ ] 導入支援者への状況共有
- [ ] 改正施行

**Comment by knokmki612** [comment]
以下の指摘があり、なんらかの対応をおこなう必要が生じた

> 事務取次会社様より、「育児・介護休業規程」の修正案がまいりましたので、連携致します。
> 
> - ヘッダーに　社名を追加
> - 従業員　⇒　社員
> - 有期契約従業員　⇒　有期契約社員（期間に定めのある社員）
> - 給与については、別途定める給与規定に基づく・・・  
> ⇓  
> 賃金については、就業規則に定める賃金規定に基づく
> - 最終ページに追記  
> 
> > 第23条（介護休業期間中の社会保険料の取扱い）
> > 
> > 介護休業により賃金が支払われない月における社会保険料の被保険者負担分は、各月に会社が納付した額を翌月●●日までに従業員に請求するものとし、社員は会社が指定する日までに支払うものとする
> > 
> > 第24条　（法令との関係）
> > 
> > 育児・介護休業、子の看護休暇、介護休暇、育児・介護のための所定外労働の制限、育児・介護のための時間外労働及び深夜業の制限並びに所定労働時間の短縮措置等に関して、この規程に定めのないことについては、育児・介護休業法その他の法令の定めるところによる。  
> 
> 上記２つの条は、厚生労働省からの明記指示によります。　　上記の赤字部分の日付を教えてください。

いただいた修正案 [育児介護休業規程202303.docx](https://github.com/tuqulore/employee-handbook/files/11037263/202303.docx)

---

> ヘッダーに　社名を追加

体裁の観点のみであれば変更なしではダメなんだろうか

> - 従業員　⇒　社員
> - 有期契約従業員　⇒　有期契約社員（期間に定めのある社員）

解釈として誤解ない記載であっても名称が不統一だとダメなんだろうか（規定例から最低限の変更をするという観点）

> - 給与については、別途定める給与規定に基づく・・・  
> ⇓  
> 賃金については、就業規則に定める賃金規定に基づく

賃金規程を参照する必要があることはたしかなので、妥当な気がする
ただし給与を賃金に一括置換しているのはやりすぎな気がする（規定例から最低限の変更をするという観点）

規定例の第23条以降が消えているのは意図しない変更な気がするので、まずは規定例と同じものを追加する必要があるように思う

@Takashi-U 個別に案へのコメントを書いてみましたが、意見いただきたいです

**Comment by knokmki612** [comment]
> > - 従業員　⇒　社員
> > - 有期契約従業員　⇒　有期契約社員（期間に定めのある社員）
> 
> 解釈として誤解ない記載であっても名称が不統一だとダメなんだろうか（規定例から最低限の変更をするという観点）

どのみち統一するならと #118 にて就業規則等を従業員に統一する変更を下書きしました（方針として適切かから確認が必要と思います）

**Comment by Takashi-U** [comment]
結論から言えば、先方が修正を必要と考える（修正しなければ年金の件が先に進まない）のであれば、修正しなければならないのかなと思います。それに対して修正の副作用としては法的に何か問題が発生するかと言えば、発生する事は想起されないので、修正に応じる事は差し支えないかと存じます。

以下は意見を求められた事項についての考え方です。

▼語句についての基本的な捉え方

先ず、こういった規程については、従業員と社員という言葉が混在するという事はNGというのが通常の考え方になります。仮に従業員と社員という言葉が混在していたら、同じ意味を持っているという可能性を完全に排除しないまでも、あえて違う言葉を使っているので違う意味があるのだろうと読み進める事になります。
この事から、語句を統一するという事については必要であると言えます。解釈として誤解無い記載であったとしても、法的な書面の読み方として「違う言葉は違う意味」となるわけですから、違う言葉にしているだけで脆弱性があると考えるべきかと存じます。

次に、語句の統一は必要でありますが、ではどの様な語句が相応しいのかという問題が残ります。コメントいただいた語句について個別に考え方を記載します。

▼従業員と社員、有期契約○○

どちらでも良いかと存じます。
ただし、こちらは他でもコメントをした記憶がありますが、この二つのどちらかで選べと言われれば従業員の方がベターであると考えます。社員という言葉は国語辞典的には従業員とほぼ同様な意味で扱われますが、会社法や社団法人法など「社員」を明確に定義している法律がある事から、社員という言葉を使うのを避けたいというのが理由です。

一般的な語句としての社員という事もありますが、「正社員」「パート社員」等の「○○社員」という言葉に引っ張られて、就業規則上でそれらを包括して「社員」と呼んでいるという推測も成り立つように思います。

ちなみに、前述の通り違う言葉は違う意味ですので、「正社員」は「社員」ではありません。社員という言葉を避けたいという理由と矛盾しません。「従業員」だから「有期契約従業員」と統一するのは問題ありませんし、同様に「従業員」としていても「有期契約社員」とするのも問題ありません。

とはいえ、現在就業規則上で従業員では無く社員という語句を使っている会社は多いと思いますが、上記の理由から積極的に変更までする必要があるのかと言えば、私見ではありますがそこまでの必要は無いと考えます。社員から従業員への変更（逆の場合）も同様です。

この考え方からすると冒頭の結論にはならないのですが、どうして変更するという結論にしたのかと言いますと、「従業員の方がどちらかと言えば適切なのであえて変更する必要が無い」という事を説明する方が、コストがかかると思ったからです。私だったら「社員よりも従業員という言葉が相応しいので直してください」とは言わない上に、かつ、ベターでは無い方への修正を提案されているという二つの事柄から、説得のコストが高いという印象を持ってしまいまし。コストがかからないようであれば、従業員のままが良いと思います。

▼第23条と第24条の追加

この二つを追加するという事はベターであると考えます。ただ、この二つは無くてもあまり意味はありません。

徴収出来なかった社会保険料は民法上の債権債務になります。端的に言えばお金の貸し借りなので返すことは当然ですし、返し方も色々あって当人同士の契約で決めれば良いという事になります。
ベターである所以は、予め返済方法などを定めておく方が良いという考え方からです。ここで「○○日までに請求」としていると、その通りにやらないと行けないという面倒くささもありますが、都度、返済について決めるというのは法的にはリスク要因でもあります。

とはいえ、この記載が無いことが決定的に影響するとは考えがたいですし、万一何か問題があったとしても介護休業の発生頻度の少なさと、期間の短さからすれば（私が金額の大小を言うのは憚られますが）影響はかなり限定的です。そういったことからあまり意味が無いと考えた次第です。

第24条についても当たり前の内容なので、特に述べることはありません。

▼給与、賃金

こちらも元々の文「別途定める給与規定」の方が、汎用性がありますので、そのままの方がベターだと思います。結論が違うのは従業員と社員の語句と同じです。

どうしてこの表現の方を汎用性があると考えるのかを説明します。

先ず、「規定」と「規程」は意味が違うという事が挙げられます。
端的に言うと「規定」というのは各条文（の内容）を指し、「規程」というのは給与規程、退職金規程の様な条文のまとまりを指します。

次に、「給与」と「賃金」では言葉の意味が違うことが挙げられます。
賃金というのは労働の対価として受けるものですが、給与の概念はそれよりも広く、労働や会社に所属している事等に起因する金銭的な利益を指します。
例えば、恩恵的に与える会社創立記念の金一封は賃金には該当しませんが、給与には該当します。

これら二つを踏まえて元々の文を意訳しますと「別に定めてある金銭的利益に関する諸々の内容」となります。ものすごく広く捉えている事がおわかりいただけるかと思います。
逆に「別に定める賃金規程」となりますと、GitHub上にある賃金規程そのものに書いてある内容を限定している事になります。

現状は金銭的なところの規程は賃金規程しか無いので良いですが、旅費規程やら福利厚生のその他の取り決めなどが出てきた場合には、「別に定める賃金規程、旅費規程、福利厚生規程…」みたいに都度改正していく必要があります。

この事から、本件については私としては「Rubyで書けば良いものを、なんでわざわざCで書くの？」という類いの印象を持つ次第です。

もちろん、厳密に「規程」ベースで記載するのが悪いわけでは無くて、厳密さというのは法廷闘争においては有利に働くケースも有り得ます。ただし、不利に働く事もあります。
先程のRubyとCの例で言えば、言語としての優劣の問題では無くて、一長一短と言いますか、それぞれの特性の問題で、どちらかを選択するかということに過ぎません。

どういった書き方が良いのかというのは御社次第ではありますが、私のこれまでの印象としては汎用性の高い方が御社にはあっている様な気はします。

▼まとめ

長々となりましたが、この変更については規程の内容そのものが決定的に変わってくるものではありません。言葉の使い方などは法的には大事な問題ですが、個別の会社と従業員の間の問題においては意味を成さない事が殆どです。万一意味を成すときがあるとすれば、規程に決定的な語句の齟齬があった上に、会社と従業員の関係性が相当に拗れてしまっているときでしょう。
アドバイスされる方からすれば、より厳密にという考え方が働くのはよく分かります。尋ねられればどうしても「より正確に」という気持ちになってしまうと思います。

意見や見解しては上記の通り落としますので、後は先方との話で折り合っていただければと存じます。

**Comment by knokmki612** [comment]
ご回答ありがとうございます。いずれのご見解についても納得している次第です。

まずはいただいた見解をもとに先方とやりとりしようかと思います。

**Comment by knokmki612** [comment]
先方とのやりとりの結果として、以下は厚生労働省の指導があるということで対応が必要という返答でした。それ以外は変更なしということになりました。

- 第23条と第24条の追加

第23条の会社の請求日の明示は取り除いても差し支えないとご提案いただいたので、そのようにしようかと思います。

その他用語が不統一である件は確定拠出年金の運用管理機関（金融機関）、厚生労働省からの指摘を受ける可能性があるものの、まずはそのまま申請するということになりました。

上記条の追加、必要が生じた場合の用語への対応は内容に影響のあるものではないかと思うので、ツクロア内で対応していきます。

**Comment by knokmki612** [comment]
内容については現時点のもので改正の手続きを進めている状態です。 #116 #120
改めて対応する点がでてくるかもしれませんが、一旦現時点のもので申請しますので、対応完了としたいと思います。
