### ISSUE TITLE
育児介護休業規程の作成

### ISSUE THREAD

**Issue by knokmki612** [tuqulore/employee-handbook#91]
関連 #88

該当条 [第39条　育児・介護休業、子の看護休暇等](https://github.com/tuqulore/employee-handbook/blob/master/01_%E5%B0%B1%E6%A5%AD%E8%A6%8F%E5%89%87.md#%E7%AC%AC39%E6%9D%A1%E8%82%B2%E5%85%90%E4%BB%8B%E8%AD%B7%E4%BC%91%E6%A5%AD%E5%AD%90%E3%81%AE%E7%9C%8B%E8%AD%B7%E4%BC%91%E6%9A%87%E7%AD%89
)
> 育児・介護休業等の取扱いについては、育児・介護休業法の定めるところによる。

これでは認められないとの指摘をもらった。
当初は、法律では賃金扱いについて定めがないためという話だった。

私の認識としては[第46条　休暇等の賃金](https://github.com/tuqulore/employee-handbook/blob/master/01_%E5%B0%B1%E6%A5%AD%E8%A6%8F%E5%89%87.md#%E7%AC%AC46%E6%9D%A1%E4%BC%91%E6%9A%87%E7%AD%89%E3%81%AE%E8%B3%83%E9%87%91)により無給であると回答した。

最終的には、確定拠出年金にかかる申請に際して、厚生労働省から「育児介護」に関する社内規定について、厚生労働省から提出を求められるとの話だった。

**Comment by knokmki612** [comment]
規程の作成にあたり、サンプルとしていただいた
[育児・介護休業等に関する規程.docx](https://github.com/tuqulore/employee-handbook/files/10317046/default.docx)

**Comment by knokmki612** [comment]
該当箇所の経緯としては、以下のような説明をおこなった

> 1. 育児・介護休業法は頻繁に法改正されるため該当規則を追従させるのが非生産的である
> 2. 育児・介護休業法への対応は法律以上の基準を設けず、法律どおりの対応をおこなうのであれば育児・介護休業に関する規程は当面不要
> 
> と提案いただき了承しました。書きぶりそのものは私が考えたものであり、その後社労士さんのチェックを通った状態です。

**Comment by knokmki612** [comment]
https://github.com/tuqulore/employee-handbook/issues/84 のような課題もあり、基本的には規程を作成する必要性が出てきたということではあるかと思う。ただ、作成後の規程の管理と運用が容易な状態にもっていけるならその方がいいと思っている

**Comment by knokmki612** [comment]
> 規程を作成する必要性が出てきた

これに単純に対応するのであれば、

1. いただいているサンプルの育児介護休業規程のWordファイルをGoogleドキュメント等オンラインドキュメントビューワーで閲覧可能な状態にする
2. 本リポジトリからは当該ドキュメントを参照するURLを記載する

という手順がもっとも手軽かとおもう。

> 作成後の規程の管理と運用が容易な状態にもっていけるならその方がいい

この観点を考慮するならば、

育児・介護休業等に関する規則の規定例［簡易版] という簡易版の規定例が存在する。こちらをベースに本リポジトリの様式に揃えて用意していくのが現実的におもった。

簡易版は単純にボリュームが相対的に少ないのと、それに伴い運用に必要な内容の理解もしやすくなる。

https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/000103533.html

**Comment by knokmki612** [comment]
> > 規程を作成する必要性が出てきた
> 
> これに単純に対応するのであれば、
> 
> 1. いただいているサンプルの育児介護休業規程のWordファイルをGoogleドキュメント等オンラインドキュメントビューワーで閲覧可能な状態にする
> 2. 本リポジトリからは当該ドキュメントを参照するURLを記載する
> 
> という手順がもっとも手軽かとおもう。

社内で協議した結果としては、こちらで進めていくことになった

**Comment by Takashi-U** [comment]
一度拝見を致しました。
簡単なものはapproveしました。

所定労働時間の短縮の部分については変更案を記載しました。（介護の所も同じ変更が必要ですが、一先ず育児の方で内容が固まってからで良いかと思い、そちらはまだ手をつけておりません。）

実質的にはあまり意味が無いと思うところですが、1日6時間を超える要素を排除することを法律が求めていると考えますと、この様な表記になるのかなと思います。時刻については私が適当に作っていますので、ここは御社の実情になるべく近い形にしていただければと思います。
時間帯を一つにしていますが、労働者が選べるのであれば複数あっても問題ではありません。

https://jsite.mhlw.go.jp/yamanashi-roudoukyoku/library/yamanashi-roudoukyoku/kintoushitsu/kintousekoujoukyou6.pdf

こちらの資料の3ページに本件についての解説がありますので、ご参考までに共有します。

**Comment by Takashi-U** [comment]
先週お伝えするのを失念しておりましたが、Googleドキュメントの仕様なのか、章ごとに条数がリセットされて第1条から表記されてしまいます。
そうなると、参照が上手くいっていない事になりますので、この辺りは技術的な対策が必要に思います。ブラウザで見ているときだけの問題であれば良いのですが、この点ご留意ください。

**Comment by knokmki612** [comment]
ご報告ありがとうございます&私も確認しておくべき事項でした。

ナンバリングがリセットされてしまう件は手元のLibreOfficeでも起きていたので意図的なものと解釈してスルーしていました。

ナンバリングの修正はひとつ試せる方法があると思っていますので、試してみます。

**Comment by knokmki612** [comment]
> ナンバリングの修正はひとつ試せる方法があると思っていますので、試してみます。

https://support.google.com/docs/answer/3300615?hl=ja

上記ヘルプドキュメントにしたがい、「前の番号を継続」を試そうと思ったのですが、こちらのオプションが非活性になっていたので試せませんでした。

となると章番号については番号つきリストであることを諦めるほかないかと思いましたので、そのように対応します。

**Comment by knokmki612** [comment]
@Takashi-U あらかた条番号を通し番号にはできたのですが、附則についても通し番号にするのが適切でしょうかね？ (いただいたオリジナルの Word ファイルを Microsoft Office Online の Word でも確認しましたが、通し番号維持できず、元々の意図する内容が再現できなかったため確認しようかと思いまして)

**Comment by knokmki612** [comment]
内容的には、変更が必要であった点はひと通り対応できた状態かと思います（ @Takashi-U さんの視点で検討事項がない状態となりましたら、こちらのissue閉じていただくような流れで進められればと思いました ）

**Comment by Takashi-U** [comment]
@knokmki612 附則は本則とは別に通しにするのが通例かと思いますが、本則と違って附則の中で条数を参照する事は想定されませんので、条数等をつけなくても用が足りるとも思います。
現況、本来のねらいは達成できるかと思いますので検討事項は無いかと存じます。

**Comment by knokmki612** [comment]
そうしましたら附則は現状別の通し番号になっているかと思いますので、とくに変更なくとも差し支えないということで了解しました。

**Comment by knokmki612** [comment]
検討事項をひととおり解消済みと確認できましたので完了します。
