### ISSUE TITLE
定年到達者の継続雇用の取扱いがあいまい

### ISSUE THREAD

**Issue by knokmki612** [tuqulore/employee-handbook#92]
関連 #88

該当条文 [第58条　定年等](https://github.com/tuqulore/employee-handbook/blob/master/01_%E5%B0%B1%E6%A5%AD%E8%A6%8F%E5%89%87.md#%E7%AC%AC58%E6%9D%A1%E5%AE%9A%E5%B9%B4%E7%AD%89)

> 1. 社員の定年は、満60歳とし、定年に達した日の属する月の末日をもって退職とする。
> 2. 前項の規定にかかわらず、定年後も引き続き雇用されることを希望し、解雇事由又は退職事由に該当しない社員については、満65歳に達した日の属する月の末日までこれを継続雇用する。

当初は確定拠出年金にかかる申請に際して、定年退職後の再雇用者の個別契約書の提出が必要という話だった。

ただ、「継続雇用」が再雇用（一旦退職させ、再契約）なのか勤務延長（退職させず、労働条件を通知するなど）なのか未検討に思った。

私は引用部の解釈としては勤務延長にあたる取扱いを連想するので、もしそうでないのであれば、退職させ、再雇用するような旨の明記が必要かと思った。

**Comment by Tomo416** [comment]
再雇用の場合だと、
「年金受給額+給与」が28万円を超えた分はカット
これが気になる人は気になるかなあ。。
（個人的にはあまり気にならないです）

ただ、ツクロアには退職金がないぶん、勤務延長した方が退職する場合の退職金を全期間支払うことがないので、再雇用よりもメリットは多いように感じました。

**Comment by knokmki612** [comment]
個人的には、デスクワークが主な職業において、年齢を理由として職務内容、労働条件を変更するというのはあまり適当でないような気がしています

職務内容の変更は[就業規則第9条](https://github.com/tuqulore/employee-handbook/blob/master/01_%E5%B0%B1%E6%A5%AD%E8%A6%8F%E5%89%87.md#%E7%AC%AC9%E6%9D%A1%E8%81%B7%E5%8B%99%E5%86%85%E5%AE%B9%E3%81%AE%E5%A4%89%E6%9B%B4)に定めがありますし、
労働条件の変更は、（双方合意のうえで）定年到達時によらずに随時おこなえばいいようにも思います

**Comment by Hidetaro7** [comment]
年齢を理由に労働条件を変えるのは私も妥当ではないと思ってますし
年齢理由以外で労働条件を変更する必要があることも考えられる（傷病、家庭の事情など）ので定年を基準にせず、第9条の定めによって随時行う、という考えでよいと思いました。

**Comment by knokmki612** [comment]
現状としては、上記のやりとりから再雇用せず定年を延長する旨を解釈の余地がないように記載したいが、うまい書きぶりがいまいち思いつかない

**Comment by Takashi-U** [comment]
第2項は「～にもかかわらず」という出だしですので、再雇用ではなく定年延長となり、その中でもイメージとしては選択定年制の考え方に類すると思います。

コメントを拝見するに対応としては、

1. 第1項の60歳を65歳として、第2項は削除
2. 基本的にはそのまま（解雇事由等の文言はなくて良いかなと）

の2択あたりが有力かと思います。

1は説明不要かと思いますが、2について補足します。

あえて60歳と65歳の2段階を設定するというのは、労働者目線からすれば60歳で退職したとしても「退職金がもらえる（会社の規程によります）」「自己都合ではなく定年退職となる」という利点があり、それを選択できるオプションがあるという形になります。
労働者側のデメリットとしては、法的には労働者側のオプションなので基本的にはありません。

会社側のメリットとしては、早期退職を促す（こちらは業務状況によってはデメリットになり得ます）極弱い効果があり人件費を抑制出来ること位でしょうが、括弧書きの通りデメリットになる可能性がものすごく高いと思います。

長年勤めている人がいて、旧規定が60歳となっているというようなケースで、定年を65歳に引き上げるに際して不利益が無いように（60歳から第2の人生を歩みたい人が定年出来なくなってしまう）残しておく、労働者へのオプションとして設定するという様な意図がないならば、シンプルに65歳にしてしまう方が手間もないですし、難しい事を考えずにすみます。

**Comment by Takashi-U** [comment]
> 年齢を理由に労働条件を変えるのは私も妥当ではないと思ってますし 年齢理由以外で労働条件を変更する必要があることも考えられる（傷病、家庭の事情など）ので定年を基準にせず、第9条の定めによって随時行う、という考えでよいと思いました。

御社の就業規則上（労働基準法上）は全く問題ありませんが、この場合雇用保険の手続上は基本的に自己都合退職（正当な事由の有無の違いは場合によって発生します）という事になってしまいます。
雇用保険上で定年を事由にするには、就業規則等で規定されている定年退職日ぴったりで退職する必要がありますので、その点はご留意ください。

**Comment by knokmki612** [comment]
元々私が定年60歳で起案した経緯としては、社内に定年が近い者がいないこともあってか、いち20代の労働者の視点として60歳まで勤め上げるというのもなかなか想像つかず、65歳、70歳は言うまでもなくさらに想像し難いという印象がありました。

> 長年勤めている人がいて、旧規定が60歳となっているというようなケースで、定年を65歳に引き上げるに際して不利益が無いように（60歳から第2の人生を歩みたい人が定年出来なくなってしまう）残しておく、労働者へのオプションとして設定するという様な意図がないならば、シンプルに65歳にしてしまう方が手間もないですし、難しい事を考えずにすみます。

この点の判断は私からだとどうしても当事者としては早期退職のオプションを残しておきたいという気持ちに傾いてしまいますので、経営者視点で @Hidetaro7 の意見が必要かと思いました。

**Comment by Hidetaro7** [comment]
長く働きたくない人もいれば、その逆の人もいるため、どこで判断したらよいのかわからない、というのが正直な答えです。

この先、定年が一般的に引き上げられていくかもしれないので、世の中の状況を見ながら改定する可能性を残しつつ今は65歳ということでいいのかもしれません。

**Comment by knokmki612** [comment]
それでは65歳定年ということですすめますか

---

本質的には定年を廃止するというのも合理的に思えたのですが、定年による自然退職がない点での不都合がどの程度あるのか等いまいち分からず、お伺いしてみたいところです @Takashi-U

**Comment by Takashi-U** [comment]
@knokmki612 お手間を入れてましてすみません。
労働者目線で定年が無い事の不利益としては、雇用保険上は自己都合退職になってしまう事が大きいと思います。ただ、これについては65歳以上であれば支給停止期間が違うだけで、給付日数が変わるわけではありませんし、また、何よりも定年が無い方が長く勤める事が出来るので、そのメリットがあまりにも大きすぎるため、不都合は無いとまで言って良いように思います。（私の価値観です。）

一方、会社側はかなりデメリットがあります。
長く働いてもらいたいと思っていても、加齢による能力の低下や、会社としての新陳代謝が鈍るという事は現実問題として起こりうる所です。御社の様な業種はまだしも、例えば建設業で現場仕事をされている様な労働者の場合は、加齢による衰えの影響は顕著で、下手をすれば重大な事故を起こすことも有り得ます。
こういった事を考えますと、どこかのタイミングで退職をしていただいたり、あるいは、再雇用等で業務を制限したり変更したりという事は、会社運営という事を考えると（長く働いて貰いたいという気持ちがあったとしても）、ある程度は実施していく必要があるところです。
それぞれに加齢の影響は違うわけですから一概に言えませんが、まだまだ働ける方は定年後もそのまま継続雇用すれば良いですし、そうで無い方については退職や再雇用という事で御願いをすればよく、会社はオプションがあった方が有利である事は間違いありません。

御社だと定年廃止というのもありうるとは思いますが、まだ皆さんお若いわけですから、今ここで決めるよりは無難に65歳定年にしておくのがベターであると思います。

**Comment by knokmki612** [comment]
現状無難な一律定年制度へと見直すということで了解しました。
