### ISSUE TITLE
労働者→社員

### ISSUE THREAD

**Issue by knokmki612** [tuqulore/employee-handbook#95]
関連 #88 

該当条文 [第10条　休職](https://github.com/tuqulore/employee-handbook/blob/master/01_%E5%B0%B1%E6%A5%AD%E8%A6%8F%E5%89%87.md#%E7%AC%AC10%E6%9D%A1%E4%BC%91%E8%81%B7)

> 労働者が、次のいずれかに該当するときは、所定の期間休職とする。

こちら社員と記載可能ではないかと指摘いただいた

**Comment by Takashi-U** [comment]
表記が統一されている事と、その表記の定義が定まっている事の2点が重要なので、ご指摘いただいたとおりの対応が良いかと存じます。私も細かい文言まで気がつかずすみません。

以下余談です。
この規則で言うところの社員というのは、一般的な辞書的な意味での社員（会社員）の事を指していると思われます。
法律の話をすると株式会社の社員というのは株主の事を指すため、どちらかと言えば労働者とか従業員という表記をする事が多いと思います。例えば厚生労働省のモデル就業規則では労働者となっております。
これは想像ですが、当初の原案では各規定の全部または一部に労働者という文言が使われており、当該条文はそれをreplaceするのが漏れてそのまま残っていたと思われます。
他の規則や条文をこの観点では見ていませんが、もしもそういった箇所があれば、表記を統一する方向で対応をされたら良いでしょう。

**Comment by knokmki612** [comment]
> この規則で言うところの社員というのは、一般的な辞書的な意味での社員（会社員）の事を指していると思われます。

おっしゃるとおりかとおもいます。経緯としては最初に就業規則を作成する段階で、法的に意味のある名称か否か考慮せず（なんとなく労働者だと古めかしい印象という程度）で社員に名称変更したと記憶しています。

今の感覚としては労働者か従業員に名称を改めたほうが不必要な解釈の余地を生まないという点でよりよいように思いました。

現時点としては表記を社員に統一しつつ、別途名称変更について残タスクとして残しておくのがよさそうに思いました。
