### ISSUE TITLE
休暇等が指し示すものがあいまい

### ISSUE THREAD

**Issue by knokmki612** [tuqulore/employee-handbook#96]
関連 #88

該当条文 [第46条　休暇等の賃金](https://github.com/tuqulore/employee-handbook/blob/master/01_%E5%B0%B1%E6%A5%AD%E8%A6%8F%E5%89%87.md#%E7%AC%AC46%E6%9D%A1%E4%BC%91%E6%9A%87%E7%AD%89%E3%81%AE%E8%B3%83%E9%87%91)

> 前項を除く休暇等の期間は、無給とする。

休暇等になにが含まれるのかあいまいではないかという指摘を直接もらったわけではないが、

- 休職
- 育児・介護休業等

について賃金の定めがないようにも読み取れる様子（私からは該当部分のとおり無給であると回答）

明確に指し示す範囲を記載した方がよいかと思った。

**Comment by knokmki612** [comment]
> 育児・介護休業等

こちらについては[育児介護休業規程](https://docs.google.com/document/d/1RqRhLP7J-L6kVuQCyGKkswMWZh0ZS-2ID_c-fkYoidY/view)の第4章第1条の記載をそのまま残すかと思われる。 
 
> 1. 育児・介護休業の期間については、基本給その他の月毎に支払われる給与は支給しない。
> 2. 賞与については、その算定対象期間に育児・介護休業をした期間が含まれる場合には、出勤日数により日割りで計算した額を支給する。

と思うと必要なのは休職が含まれている旨の明示くらいだろうか？

**Comment by knokmki612** [comment]
「休暇等」が指し示すものは第6章に規定のあるものを期待するような気がするので、休職は別の条にしたほうがいいのだろうか？ともあれとりあえず書いてみてレビューに回させてください

**Comment by Takashi-U** [comment]
第6章のタイトルが「休暇等」となっており、この場合は辞書的な一般的な意味ではなく、第6章そのものを表すと考えるべきかと思います。その点では

> 「休暇等」が指し示すものは第6章に規定のあるものを期待するような気がする

このご認識は全く正しいかと存じます。

また、一般的には「ノーワークノーペイの原則」というものがありまして、これは、働いていない（労務の提供という義務を果たしていない）以上は原則として賃金を支払わなくて良いというものです。この原則の例外は年次有給休暇だけで、その他の休みは、休暇や休業等の名称の如何を問わず無給であって差し支えありません。
さらに、御社は賃金規程で時給制を採用していることから、いわゆる完全月給制のように出勤実績を問わず支給される賃金形態ではなく、現況の規則においても特に曖昧では無いように思います。

もっとも、今回の追記は読み手にとっては親切な変更ですので、現況に問題があるかどうかは別として取り入れるべき変更だと感じております。記載の場所は第10条が良いように思いますので、その点はレビューに残しておきたいと思います。

ちなみにですが、「休暇」「休業」「休職」と似たような言葉が使われておりますが、第10条の休職が他の休みと違う側面として「条件が揃ったら自動的に労働の義務を一時的に無くす（そもそも義務が無い状態にする）」という部分が挙げられます。この休職についてはそもそも労働の義務が無いわけですから、反対給付である賃金は発生しないと考える事が出来ます。
しばしばいただく相談に、御社で言うところの第10条の休職の際には有給休暇が取れるのかというものがあります。答えとしては、前述の通り労働の義務が無いので、有給休暇は取る事が出来ないという話になります。（労働者優位に取り扱うために取らせてあげることにはガバナンスはさておき、会社と当該労働者の間においては問題は無いとは思いますが。）

反対に病欠の様なケースはどの様に考えるかというと「労働の義務はあるものの、その義務を免除する」という形になります。労働の義務を免除しているから、反対給付の賃金の支払も無くなるのが原則になるのは、当然といえば当然です。
ちなみに、元々労働の義務があるからこそ、風邪を引いたときに有給休暇を取得する余地が出てくるわけで、ここが休職に突入したときの違いとなります。

恐らく、御社の規則においては元々の労働義務のある休暇について第6章に記載し、さらに、視認性と言いますか、看護休暇等の絡みも考えるとバラバラにすると余計にややこしい事になるため、育児介護休業などの労働の義務そのものがなくなる休業ではあるものの一緒に第6章としているという立て付けなのかと推察します。
そして、先ほど、労働の義務を免除しているから反対給付の賃金が無くなるという形で言及しましたが、労働の義務を免除したからと言って、反対給付も当然に免除になるかどうかは必ずしも分かりません。（だからこそ、原則という表現をしました。）
そのため、労働の義務を免除するケース（御社で言う所の休暇）においては、念のため給与が無い事をハッキリとさせるというのが、第46条の本旨であると思われます。第10条の休職への給与に対する言及が無いのも、こう考えると自然といえば自然ではあります。

やはりこの様に考えると、原理原則から考えるとある程度自明であっても、直感的に分からないものは曖昧と殆ど変わらないので、書き加えることが妥当なのでしょう。

**Comment by knokmki612** [comment]
ありがとうございます。変更前の状況としては休職の賃金の取り扱いについては明記しておらず、原則的に考えると無給と読むのが適切な状態であると理解しました。
そのうえで提出中のPRにより休職中の賃金の取り扱い明記する（読み手への）メリットがあると理解しました。
