### ISSUE TITLE
産前産後の女性→産前産後の女性社員

### ISSUE THREAD

**Issue by knokmki612** [tuqulore/employee-handbook#97]
関連 #88

該当条文 [第35条　年次有給休暇の付与日数算定に係る勤務日等の対象日](https://github.com/tuqulore/employee-handbook/blob/master/01_%E5%B0%B1%E6%A5%AD%E8%A6%8F%E5%89%87.md#%E7%AC%AC35%E6%9D%A1%E5%B9%B4%E6%AC%A1%E6%9C%89%E7%B5%A6%E4%BC%91%E6%9A%87%E3%81%AE%E4%BB%98%E4%B8%8E%E6%97%A5%E6%95%B0%E7%AE%97%E5%AE%9A%E3%81%AB%E4%BF%82%E3%82%8B%E5%8B%A4%E5%8B%99%E6%97%A5%E7%AD%89%E3%81%AE%E5%AF%BE%E8%B1%A1%E6%97%A5)

> 産前産後の女性が労基法65条の定めにより休業した期間

社員である旨明記した方がよいのではないかと指摘いただいた

**Comment by Takashi-U** [comment]
この変更については、ちょっと違和感があるとは思います（法律的な所ではなく、私の感覚）が、特に支障は無いと思います。

この条文に限って言えばですが、ここに社員をつけるとなると、例えば他の号も「 業務上の負傷又は疫病により社員が休業した期間」「社員が年次有給休暇を取得した期間」となる様に思います。
号というレイヤーなので「社員」を省略して簡略に表記をしているので、「女性社員」のうち「社員」が省略されたという様に見えます。親クラスで「社員」が定義してあって、継承した子クラスでは書かないようなものでしょう。

恐らく、他の条文で「女性社員」となっている事からこの様なご提案をいただいたのだと思います。それもまた一つの感覚だと思います。

雑談でした。（何も言葉を添えずにOKするのもアレかと思いまして…）

**Comment by knokmki612** [comment]
> 親クラスで「社員」が定義してあって、継承した子クラスでは書かないようなものでしょう。

おっしゃるように、文脈として社員に関する規定と明らかにもかかわらずあらためて社員であることの記載をおこなうのは、しても支障ないが不必要な変更にも思えますね

**Comment by knokmki612** [comment]
これはWont fixとしたほうがいい気がしました。このまま閉じます。
